### ISSUE TITLE
Injection methods in 2020 be like

### ISSUE THREAD

**Issue by themaoci** [voidzero-development/Secure-Tarkov-Loader#1]
https://docs.microsoft.com/en-au/dotnet/api/system.io.file.copy?view=netcore-3.1

👍 👍 👍 👍 👍

**Comment by voidzero666** [comment]
https://www.learncpp.com/

**Comment by themaoci** [comment]
https://github.com/voidzero-development/Secure-Tarkov-Loader/blob/master/Loader/Loader.cpp#L151
https://github.com/voidzero-development/Secure-Tarkov-Loader/blob/master/Loader/Loader.cpp#L38

its literally get file load as binary then override original one which is literally equivalent of File.Copy in c#

```
std::cout << "found, injecting!" << std::endl;
```
==>
```
std::cout << "found, replacing file!" << std::endl;
```

that is what i mean here

**Comment by voidzero666** [comment]
Yeah, and? This is old hence why it is public. Nobody cares about the injection method anyway was you can plug in any you desire.
